Bash script fixe for sflphone-qt and sflphone-cli Fixe for no username bugs

diff --git a/src/sflphone.in b/src/sflphone.in
--- a/src/sflphone.in
+++ b/src/sflphone.in
@@ -10,28 +10,37 @@ export LD_LIBRARY_PATH
 
 message="Warning, you probably did not extract the archive in the / directory,
 you must edit this script ($0) and change SFLPHONE_DIR to the correct location.
-%libexecdir% must contain the provided libraries."
-if [ ! -d ${SFLPHONE_DIR} ]
-then
-	echo $message
-	exit 1
+@libexecdir@ must contain the provided libraries."
+if [ ! -d ${SFLPHONE_DIR} ]; then
+  echo $message
+  exit 1
 else
-		if [ ! -d @libexecdir@ ]
-		then
-			echo $message
-			exit 1
-		fi
+  if [ ! -d @libexecdir@ ]; then
+    echo $message
+    exit 1
+  fi
 fi
 
 # Let's try to go..
 PATH=@libexecdir@:${PATH}
-binary=@libexecdir@/sflphone-qt.bin
-if [ -x ${binary} ]
-then
-	exec $binary
-else
-	echo "Could not find the sflphone-qt.bin executable in %libexecdir% !"
-	exit 1
+binaryqtname=sflphone-qt
+binaryqt=@libexecdir@/${binaryqtname}
+binarycliname=sflphone-cli
+binarycli=@libexecdir@/${binarycliname}
+if [ "$1" != "--text" ]; then
+  if [ -x ${binaryqt} ]; then
+    exec $binaryqt
+  else
+    echo "Could not find the ${binaryqtname} executable in @libexecdir@ !"
+    exit 1
+  fi
+else 
+  if [ -x ${binarycli} ]; then
+    SFLPHONE_CORE_DIR=@libexecdir@ exec $binarycli
+  else
+    echo "Could not find the ${binarycliname} executable in @libexecdir@ !"
+    exit 1
+  fi
 fi
 
 # EOF
